development:
  host: "localhost:3000"
  email_from: "fabianraf@gmail.com" 
preview:
    host: "andesconexion-preview.visualdyc.com"
    email_from: "info@andesconexion.com"
production:
    host: "www.andesconexion.com"
    email_from: "info@andesconexion.com"